class GestureRecognizer {
    constructor() {       
        this.class_names = ["I", "U", "INFINITY", "<", "O", "L", "e", "M"];
        this.initialized = false;
    }

    async _init() {
        if (!this.initialized) {
            this.session = await ort.InferenceSession.create("./pyrocket2.onnx");
            this.initialized = true;
        }
    }

    argMax(array) {
        return [].map.call(array, (x, i) => [x, i]).reduce((r, a) => (a[0] > r[0] ? a : r))[1];
    }

    async inference(ControllerInput) {
        await this._init();
        let GestureSequenceLength = ControllerInput[0].length;
        //Concatenation of(X, Y, Z) controller data
        let Concatenate = ControllerInput[0].concat(ControllerInput[1], ControllerInput[2]);
        const input0 = new ort.Tensor(new Float32Array(Concatenate), [1, 3, GestureSequenceLength]);
        const outputs = await this.session.run({ input: input0 });
        //consume the output
        const outputTensor = outputs["output"];
        //Converting into one dimensional array probabilities generated by ONNX model
        const probabilities = Array.from(outputTensor.data);
        const class_id = this.argMax(probabilities)
        const class_name = this.class_names[class_id]

        return {
            "class_id": class_id,
            "class_name": class_name,
            "class_probabilities" : probabilities
        };
    }
}